// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EgoObjectFormat.proto

#include "EgoObjectFormat.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class EgoObjectFormatDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EgoObjectFormat>
      _instance;
} _EgoObjectFormat_default_instance_;
namespace protobuf_EgoObjectFormat_2eproto {
void InitDefaultsEgoObjectFormatImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::EgoObjectFormat::_default_name_.DefaultConstruct();
  *::EgoObjectFormat::_default_name_.get_mutable() = ::std::string("ego", 3);
  ::google::protobuf::internal::OnShutdownDestroyString(
      ::EgoObjectFormat::_default_name_.get_mutable());
  ::EgoObjectFormat::_default_osgfile_.DefaultConstruct();
  *::EgoObjectFormat::_default_osgfile_.get_mutable() = ::std::string("../Data/robot.osg", 17);
  ::google::protobuf::internal::OnShutdownDestroyString(
      ::EgoObjectFormat::_default_osgfile_.get_mutable());
  {
    void* ptr = &::_EgoObjectFormat_default_instance_;
    new (ptr) ::EgoObjectFormat();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::EgoObjectFormat::InitAsDefaultInstance();
}

void InitDefaultsEgoObjectFormat() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsEgoObjectFormatImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EgoObjectFormat, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EgoObjectFormat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EgoObjectFormat, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EgoObjectFormat, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EgoObjectFormat, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::EgoObjectFormat, osgfile_),
  3,
  0,
  2,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::EgoObjectFormat)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_EgoObjectFormat_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "EgoObjectFormat.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025EgoObjectFormat.proto\032\016BaseType.proto\""
      "\207\001\n\017EgoObjectFormat\0221\n\004type\030\001 \002(\0162\017.TP_O"
      "BJECT_TYPE:\022TP_OBJECT_TYPE_EGO\022\021\n\004name\030\003"
      " \002(\t:\003ego\022\n\n\002id\030\004 \002(\005\022\"\n\007osgFile\030\005 \001(\t:\021"
      "../Data/robot.osg"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 177);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "EgoObjectFormat.proto", &protobuf_RegisterTypes);
  ::protobuf_BaseType_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_EgoObjectFormat_2eproto

// ===================================================================

void EgoObjectFormat::InitAsDefaultInstance() {
}
::google::protobuf::internal::ExplicitlyConstructed< ::std::string> EgoObjectFormat::_default_name_;
::google::protobuf::internal::ExplicitlyConstructed< ::std::string> EgoObjectFormat::_default_osgfile_;
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EgoObjectFormat::kTypeFieldNumber;
const int EgoObjectFormat::kNameFieldNumber;
const int EgoObjectFormat::kIdFieldNumber;
const int EgoObjectFormat::kOsgFileFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EgoObjectFormat::EgoObjectFormat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_EgoObjectFormat_2eproto::InitDefaultsEgoObjectFormat();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:EgoObjectFormat)
}
EgoObjectFormat::EgoObjectFormat(const EgoObjectFormat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::EgoObjectFormat::_default_name_.get());
  if (from.has_name()) {
    name_.AssignWithDefault(&::EgoObjectFormat::_default_name_.get(), from.name_);
  }
  osgfile_.UnsafeSetDefault(&::EgoObjectFormat::_default_osgfile_.get());
  if (from.has_osgfile()) {
    osgfile_.AssignWithDefault(&::EgoObjectFormat::_default_osgfile_.get(), from.osgfile_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&id_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:EgoObjectFormat)
}

void EgoObjectFormat::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::EgoObjectFormat::_default_name_.get());
  osgfile_.UnsafeSetDefault(&::EgoObjectFormat::_default_osgfile_.get());
  id_ = 0;
  type_ = 1;
}

EgoObjectFormat::~EgoObjectFormat() {
  // @@protoc_insertion_point(destructor:EgoObjectFormat)
  SharedDtor();
}

void EgoObjectFormat::SharedDtor() {
  name_.DestroyNoArena(&::EgoObjectFormat::_default_name_.get());
  osgfile_.DestroyNoArena(&::EgoObjectFormat::_default_osgfile_.get());
}

void EgoObjectFormat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EgoObjectFormat::descriptor() {
  ::protobuf_EgoObjectFormat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_EgoObjectFormat_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EgoObjectFormat& EgoObjectFormat::default_instance() {
  ::protobuf_EgoObjectFormat_2eproto::InitDefaultsEgoObjectFormat();
  return *internal_default_instance();
}

EgoObjectFormat* EgoObjectFormat::New(::google::protobuf::Arena* arena) const {
  EgoObjectFormat* n = new EgoObjectFormat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EgoObjectFormat::Clear() {
// @@protoc_insertion_point(message_clear_start:EgoObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!name_.IsDefault(&::EgoObjectFormat::_default_name_.get()));
      (*name_.UnsafeRawStringPointer())->assign(*&::EgoObjectFormat::_default_name_.get());
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!osgfile_.IsDefault(&::EgoObjectFormat::_default_osgfile_.get()));
      (*osgfile_.UnsafeRawStringPointer())->assign(*&::EgoObjectFormat::_default_osgfile_.get());
    }
  }
  if (cached_has_bits & 12u) {
    id_ = 0;
    type_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool EgoObjectFormat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EgoObjectFormat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_EGO];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::TP_OBJECT_TYPE_IsValid(value)) {
            set_type(static_cast< ::TP_OBJECT_TYPE >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                1, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string name = 3 [default = "ego"];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "EgoObjectFormat.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string osgFile = 5 [default = "../Data/robot.osg"];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_osgfile()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->osgfile().data(), static_cast<int>(this->osgfile().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "EgoObjectFormat.osgFile");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EgoObjectFormat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EgoObjectFormat)
  return false;
#undef DO_
}

void EgoObjectFormat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EgoObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_EGO];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // required string name = 3 [default = "ego"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "EgoObjectFormat.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // required int32 id = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->id(), output);
  }

  // optional string osgFile = 5 [default = "../Data/robot.osg"];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->osgfile().data(), static_cast<int>(this->osgfile().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "EgoObjectFormat.osgFile");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->osgfile(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:EgoObjectFormat)
}

::google::protobuf::uint8* EgoObjectFormat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:EgoObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_EGO];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // required string name = 3 [default = "ego"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "EgoObjectFormat.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // required int32 id = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->id(), target);
  }

  // optional string osgFile = 5 [default = "../Data/robot.osg"];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->osgfile().data(), static_cast<int>(this->osgfile().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "EgoObjectFormat.osgFile");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->osgfile(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EgoObjectFormat)
  return target;
}

size_t EgoObjectFormat::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:EgoObjectFormat)
  size_t total_size = 0;

  if (has_name()) {
    // required string name = 3 [default = "ego"];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  if (has_id()) {
    // required int32 id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  if (has_type()) {
    // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_EGO];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  return total_size;
}
size_t EgoObjectFormat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EgoObjectFormat)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000d) ^ 0x0000000d) == 0) {  // All required fields are present.
    // required string name = 3 [default = "ego"];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());

    // required int32 id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());

    // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_EGO];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional string osgFile = 5 [default = "../Data/robot.osg"];
  if (has_osgfile()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->osgfile());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EgoObjectFormat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EgoObjectFormat)
  GOOGLE_DCHECK_NE(&from, this);
  const EgoObjectFormat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EgoObjectFormat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EgoObjectFormat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EgoObjectFormat)
    MergeFrom(*source);
  }
}

void EgoObjectFormat::MergeFrom(const EgoObjectFormat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EgoObjectFormat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::EgoObjectFormat::_default_name_.get(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_osgfile();
      osgfile_.AssignWithDefault(&::EgoObjectFormat::_default_osgfile_.get(), from.osgfile_);
    }
    if (cached_has_bits & 0x00000004u) {
      id_ = from.id_;
    }
    if (cached_has_bits & 0x00000008u) {
      type_ = from.type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void EgoObjectFormat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EgoObjectFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EgoObjectFormat::CopyFrom(const EgoObjectFormat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EgoObjectFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EgoObjectFormat::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000d) != 0x0000000d) return false;
  return true;
}

void EgoObjectFormat::Swap(EgoObjectFormat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EgoObjectFormat::InternalSwap(EgoObjectFormat* other) {
  using std::swap;
  name_.Swap(&other->name_);
  osgfile_.Swap(&other->osgfile_);
  swap(id_, other->id_);
  swap(type_, other->type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EgoObjectFormat::GetMetadata() const {
  protobuf_EgoObjectFormat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_EgoObjectFormat_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
