// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LaneClothidObjectFormat.proto

#ifndef PROTOBUF_LaneClothidObjectFormat_2eproto__INCLUDED
#define PROTOBUF_LaneClothidObjectFormat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BaseType.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_LaneClothidObjectFormat_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsLaneClothidObjectFormatImpl();
void InitDefaultsLaneClothidObjectFormat();
inline void InitDefaults() {
  InitDefaultsLaneClothidObjectFormat();
}
}  // namespace protobuf_LaneClothidObjectFormat_2eproto
class LaneClothidObjectFormat;
class LaneClothidObjectFormatDefaultTypeInternal;
extern LaneClothidObjectFormatDefaultTypeInternal _LaneClothidObjectFormat_default_instance_;

// ===================================================================

class LaneClothidObjectFormat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LaneClothidObjectFormat) */ {
 public:
  LaneClothidObjectFormat();
  virtual ~LaneClothidObjectFormat();

  LaneClothidObjectFormat(const LaneClothidObjectFormat& from);

  inline LaneClothidObjectFormat& operator=(const LaneClothidObjectFormat& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LaneClothidObjectFormat(LaneClothidObjectFormat&& from) noexcept
    : LaneClothidObjectFormat() {
    *this = ::std::move(from);
  }

  inline LaneClothidObjectFormat& operator=(LaneClothidObjectFormat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneClothidObjectFormat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LaneClothidObjectFormat* internal_default_instance() {
    return reinterpret_cast<const LaneClothidObjectFormat*>(
               &_LaneClothidObjectFormat_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(LaneClothidObjectFormat* other);
  friend void swap(LaneClothidObjectFormat& a, LaneClothidObjectFormat& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LaneClothidObjectFormat* New() const PROTOBUF_FINAL { return New(NULL); }

  LaneClothidObjectFormat* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LaneClothidObjectFormat& from);
  void MergeFrom(const LaneClothidObjectFormat& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LaneClothidObjectFormat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float clothidPar = 6;
  int clothidpar_size() const;
  void clear_clothidpar();
  static const int kClothidParFieldNumber = 6;
  float clothidpar(int index) const;
  void set_clothidpar(int index, float value);
  void add_clothidpar(float value);
  const ::google::protobuf::RepeatedField< float >&
      clothidpar() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_clothidpar();

  // required string name = 3 [default = "Clothid Line"];
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required .Color color = 7;
  bool has_color() const;
  void clear_color();
  static const int kColorFieldNumber = 7;
  const ::Color& color() const;
  ::Color* release_color();
  ::Color* mutable_color();
  void set_allocated_color(::Color* color);

  // required int32 id = 4;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 4;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required int32 width = 8;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 8;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // required int32 length = 9;
  bool has_length() const;
  void clear_length();
  static const int kLengthFieldNumber = 9;
  ::google::protobuf::int32 length() const;
  void set_length(::google::protobuf::int32 value);

  // optional int32 pairID = 10;
  bool has_pairid() const;
  void clear_pairid();
  static const int kPairIDFieldNumber = 10;
  ::google::protobuf::int32 pairid() const;
  void set_pairid(::google::protobuf::int32 value);

  // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_S_LANE];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::TP_OBJECT_TYPE type() const;
  void set_type(::TP_OBJECT_TYPE value);

  // @@protoc_insertion_point(class_scope:LaneClothidObjectFormat)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_name();
  void clear_has_name();
  void set_has_id();
  void clear_has_id();
  void set_has_color();
  void clear_has_color();
  void set_has_width();
  void clear_has_width();
  void set_has_length();
  void clear_has_length();
  void set_has_pairid();
  void clear_has_pairid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > clothidpar_;
  static ::google::protobuf::internal::ExplicitlyConstructed< ::std::string> _default_name_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::Color* color_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 length_;
  ::google::protobuf::int32 pairid_;
  int type_;
  friend struct ::protobuf_LaneClothidObjectFormat_2eproto::TableStruct;
  friend void ::protobuf_LaneClothidObjectFormat_2eproto::InitDefaultsLaneClothidObjectFormatImpl();
};
// ===================================================================


// ===================================================================

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LaneClothidObjectFormat

// required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_S_LANE];
inline bool LaneClothidObjectFormat::has_type() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void LaneClothidObjectFormat::set_has_type() {
  _has_bits_[0] |= 0x00000040u;
}
inline void LaneClothidObjectFormat::clear_has_type() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void LaneClothidObjectFormat::clear_type() {
  type_ = 6;
  clear_has_type();
}
inline ::TP_OBJECT_TYPE LaneClothidObjectFormat::type() const {
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.type)
  return static_cast< ::TP_OBJECT_TYPE >(type_);
}
inline void LaneClothidObjectFormat::set_type(::TP_OBJECT_TYPE value) {
  assert(::TP_OBJECT_TYPE_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:LaneClothidObjectFormat.type)
}

// required string name = 3 [default = "Clothid Line"];
inline bool LaneClothidObjectFormat::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LaneClothidObjectFormat::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LaneClothidObjectFormat::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LaneClothidObjectFormat::clear_name() {
  name_.ClearToDefaultNoArena(&::LaneClothidObjectFormat::_default_name_.get());
  clear_has_name();
}
inline const ::std::string& LaneClothidObjectFormat::name() const {
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.name)
  return name_.GetNoArena();
}
inline void LaneClothidObjectFormat::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::LaneClothidObjectFormat::_default_name_.get(), value);
  // @@protoc_insertion_point(field_set:LaneClothidObjectFormat.name)
}
#if LANG_CXX11
inline void LaneClothidObjectFormat::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::LaneClothidObjectFormat::_default_name_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:LaneClothidObjectFormat.name)
}
#endif
inline void LaneClothidObjectFormat::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::LaneClothidObjectFormat::_default_name_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LaneClothidObjectFormat.name)
}
inline void LaneClothidObjectFormat::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::LaneClothidObjectFormat::_default_name_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LaneClothidObjectFormat.name)
}
inline ::std::string* LaneClothidObjectFormat::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:LaneClothidObjectFormat.name)
  return name_.MutableNoArena(&::LaneClothidObjectFormat::_default_name_.get());
}
inline ::std::string* LaneClothidObjectFormat::release_name() {
  // @@protoc_insertion_point(field_release:LaneClothidObjectFormat.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::LaneClothidObjectFormat::_default_name_.get());
}
inline void LaneClothidObjectFormat::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::LaneClothidObjectFormat::_default_name_.get(), name);
  // @@protoc_insertion_point(field_set_allocated:LaneClothidObjectFormat.name)
}

// required int32 id = 4;
inline bool LaneClothidObjectFormat::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LaneClothidObjectFormat::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LaneClothidObjectFormat::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LaneClothidObjectFormat::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 LaneClothidObjectFormat::id() const {
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.id)
  return id_;
}
inline void LaneClothidObjectFormat::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:LaneClothidObjectFormat.id)
}

// repeated float clothidPar = 6;
inline int LaneClothidObjectFormat::clothidpar_size() const {
  return clothidpar_.size();
}
inline void LaneClothidObjectFormat::clear_clothidpar() {
  clothidpar_.Clear();
}
inline float LaneClothidObjectFormat::clothidpar(int index) const {
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.clothidPar)
  return clothidpar_.Get(index);
}
inline void LaneClothidObjectFormat::set_clothidpar(int index, float value) {
  clothidpar_.Set(index, value);
  // @@protoc_insertion_point(field_set:LaneClothidObjectFormat.clothidPar)
}
inline void LaneClothidObjectFormat::add_clothidpar(float value) {
  clothidpar_.Add(value);
  // @@protoc_insertion_point(field_add:LaneClothidObjectFormat.clothidPar)
}
inline const ::google::protobuf::RepeatedField< float >&
LaneClothidObjectFormat::clothidpar() const {
  // @@protoc_insertion_point(field_list:LaneClothidObjectFormat.clothidPar)
  return clothidpar_;
}
inline ::google::protobuf::RepeatedField< float >*
LaneClothidObjectFormat::mutable_clothidpar() {
  // @@protoc_insertion_point(field_mutable_list:LaneClothidObjectFormat.clothidPar)
  return &clothidpar_;
}

// required .Color color = 7;
inline bool LaneClothidObjectFormat::has_color() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LaneClothidObjectFormat::set_has_color() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LaneClothidObjectFormat::clear_has_color() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::Color& LaneClothidObjectFormat::color() const {
  const ::Color* p = color_;
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.color)
  return p != NULL ? *p : *reinterpret_cast<const ::Color*>(
      &::_Color_default_instance_);
}
inline ::Color* LaneClothidObjectFormat::release_color() {
  // @@protoc_insertion_point(field_release:LaneClothidObjectFormat.color)
  clear_has_color();
  ::Color* temp = color_;
  color_ = NULL;
  return temp;
}
inline ::Color* LaneClothidObjectFormat::mutable_color() {
  set_has_color();
  if (color_ == NULL) {
    color_ = new ::Color;
  }
  // @@protoc_insertion_point(field_mutable:LaneClothidObjectFormat.color)
  return color_;
}
inline void LaneClothidObjectFormat::set_allocated_color(::Color* color) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(color_);
  }
  if (color) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      color = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, color, submessage_arena);
    }
    set_has_color();
  } else {
    clear_has_color();
  }
  color_ = color;
  // @@protoc_insertion_point(field_set_allocated:LaneClothidObjectFormat.color)
}

// required int32 width = 8;
inline bool LaneClothidObjectFormat::has_width() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LaneClothidObjectFormat::set_has_width() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LaneClothidObjectFormat::clear_has_width() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LaneClothidObjectFormat::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 LaneClothidObjectFormat::width() const {
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.width)
  return width_;
}
inline void LaneClothidObjectFormat::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:LaneClothidObjectFormat.width)
}

// required int32 length = 9;
inline bool LaneClothidObjectFormat::has_length() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LaneClothidObjectFormat::set_has_length() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LaneClothidObjectFormat::clear_has_length() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LaneClothidObjectFormat::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline ::google::protobuf::int32 LaneClothidObjectFormat::length() const {
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.length)
  return length_;
}
inline void LaneClothidObjectFormat::set_length(::google::protobuf::int32 value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:LaneClothidObjectFormat.length)
}

// optional int32 pairID = 10;
inline bool LaneClothidObjectFormat::has_pairid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void LaneClothidObjectFormat::set_has_pairid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void LaneClothidObjectFormat::clear_has_pairid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void LaneClothidObjectFormat::clear_pairid() {
  pairid_ = 0;
  clear_has_pairid();
}
inline ::google::protobuf::int32 LaneClothidObjectFormat::pairid() const {
  // @@protoc_insertion_point(field_get:LaneClothidObjectFormat.pairID)
  return pairid_;
}
inline void LaneClothidObjectFormat::set_pairid(::google::protobuf::int32 value) {
  set_has_pairid();
  pairid_ = value;
  // @@protoc_insertion_point(field_set:LaneClothidObjectFormat.pairID)
}

#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LaneClothidObjectFormat_2eproto__INCLUDED
