// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LaneClothidObjectFormat.proto

#include "LaneClothidObjectFormat.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class LaneClothidObjectFormatDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LaneClothidObjectFormat>
      _instance;
} _LaneClothidObjectFormat_default_instance_;
namespace protobuf_LaneClothidObjectFormat_2eproto {
void InitDefaultsLaneClothidObjectFormatImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_BaseType_2eproto::InitDefaultsColor();
  ::LaneClothidObjectFormat::_default_name_.DefaultConstruct();
  *::LaneClothidObjectFormat::_default_name_.get_mutable() = ::std::string("Clothid Line", 12);
  ::google::protobuf::internal::OnShutdownDestroyString(
      ::LaneClothidObjectFormat::_default_name_.get_mutable());
  {
    void* ptr = &::_LaneClothidObjectFormat_default_instance_;
    new (ptr) ::LaneClothidObjectFormat();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::LaneClothidObjectFormat::InitAsDefaultInstance();
}

void InitDefaultsLaneClothidObjectFormat() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsLaneClothidObjectFormatImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, clothidpar_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LaneClothidObjectFormat, pairid_),
  6,
  0,
  2,
  ~0u,
  1,
  3,
  4,
  5,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, sizeof(::LaneClothidObjectFormat)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_LaneClothidObjectFormat_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "LaneClothidObjectFormat.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035LaneClothidObjectFormat.proto\032\016BaseTyp"
      "e.proto\"\321\001\n\027LaneClothidObjectFormat\0224\n\004t"
      "ype\030\001 \002(\0162\017.TP_OBJECT_TYPE:\025TP_OBJECT_TY"
      "PE_S_LANE\022\032\n\004name\030\003 \002(\t:\014Clothid Line\022\n\n"
      "\002id\030\004 \002(\005\022\022\n\nclothidPar\030\006 \003(\002\022\025\n\005color\030\007"
      " \002(\0132\006.Color\022\r\n\005width\030\010 \002(\005\022\016\n\006length\030\t "
      "\002(\005\022\016\n\006pairID\030\n \001(\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 259);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "LaneClothidObjectFormat.proto", &protobuf_RegisterTypes);
  ::protobuf_BaseType_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_LaneClothidObjectFormat_2eproto

// ===================================================================

void LaneClothidObjectFormat::InitAsDefaultInstance() {
  ::_LaneClothidObjectFormat_default_instance_._instance.get_mutable()->color_ = const_cast< ::Color*>(
      ::Color::internal_default_instance());
}
::google::protobuf::internal::ExplicitlyConstructed< ::std::string> LaneClothidObjectFormat::_default_name_;
void LaneClothidObjectFormat::clear_color() {
  if (color_ != NULL) color_->Clear();
  clear_has_color();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LaneClothidObjectFormat::kTypeFieldNumber;
const int LaneClothidObjectFormat::kNameFieldNumber;
const int LaneClothidObjectFormat::kIdFieldNumber;
const int LaneClothidObjectFormat::kClothidParFieldNumber;
const int LaneClothidObjectFormat::kColorFieldNumber;
const int LaneClothidObjectFormat::kWidthFieldNumber;
const int LaneClothidObjectFormat::kLengthFieldNumber;
const int LaneClothidObjectFormat::kPairIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LaneClothidObjectFormat::LaneClothidObjectFormat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_LaneClothidObjectFormat_2eproto::InitDefaultsLaneClothidObjectFormat();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:LaneClothidObjectFormat)
}
LaneClothidObjectFormat::LaneClothidObjectFormat(const LaneClothidObjectFormat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      clothidpar_(from.clothidpar_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::LaneClothidObjectFormat::_default_name_.get());
  if (from.has_name()) {
    name_.AssignWithDefault(&::LaneClothidObjectFormat::_default_name_.get(), from.name_);
  }
  if (from.has_color()) {
    color_ = new ::Color(*from.color_);
  } else {
    color_ = NULL;
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&id_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:LaneClothidObjectFormat)
}

void LaneClothidObjectFormat::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::LaneClothidObjectFormat::_default_name_.get());
  ::memset(&color_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&pairid_) -
      reinterpret_cast<char*>(&color_)) + sizeof(pairid_));
  type_ = 6;
}

LaneClothidObjectFormat::~LaneClothidObjectFormat() {
  // @@protoc_insertion_point(destructor:LaneClothidObjectFormat)
  SharedDtor();
}

void LaneClothidObjectFormat::SharedDtor() {
  name_.DestroyNoArena(&::LaneClothidObjectFormat::_default_name_.get());
  if (this != internal_default_instance()) delete color_;
}

void LaneClothidObjectFormat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LaneClothidObjectFormat::descriptor() {
  ::protobuf_LaneClothidObjectFormat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_LaneClothidObjectFormat_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LaneClothidObjectFormat& LaneClothidObjectFormat::default_instance() {
  ::protobuf_LaneClothidObjectFormat_2eproto::InitDefaultsLaneClothidObjectFormat();
  return *internal_default_instance();
}

LaneClothidObjectFormat* LaneClothidObjectFormat::New(::google::protobuf::Arena* arena) const {
  LaneClothidObjectFormat* n = new LaneClothidObjectFormat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LaneClothidObjectFormat::Clear() {
// @@protoc_insertion_point(message_clear_start:LaneClothidObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clothidpar_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!name_.IsDefault(&::LaneClothidObjectFormat::_default_name_.get()));
      (*name_.UnsafeRawStringPointer())->assign(*&::LaneClothidObjectFormat::_default_name_.get());
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(color_ != NULL);
      color_->Clear();
    }
  }
  if (cached_has_bits & 124u) {
    ::memset(&id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&pairid_) -
        reinterpret_cast<char*>(&id_)) + sizeof(pairid_));
    type_ = 6;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool LaneClothidObjectFormat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LaneClothidObjectFormat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_S_LANE];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::TP_OBJECT_TYPE_IsValid(value)) {
            set_type(static_cast< ::TP_OBJECT_TYPE >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                1, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string name = 3 [default = "Clothid Line"];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "LaneClothidObjectFormat.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float clothidPar = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(53u /* 53 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 53u, input, this->mutable_clothidpar())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_clothidpar())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .Color color = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 width = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {
          set_has_width();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 length = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {
          set_has_length();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 pairID = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {
          set_has_pairid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pairid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LaneClothidObjectFormat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LaneClothidObjectFormat)
  return false;
#undef DO_
}

void LaneClothidObjectFormat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LaneClothidObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_S_LANE];
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // required string name = 3 [default = "Clothid Line"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "LaneClothidObjectFormat.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // required int32 id = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->id(), output);
  }

  // repeated float clothidPar = 6;
  for (int i = 0, n = this->clothidpar_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      6, this->clothidpar(i), output);
  }

  // required .Color color = 7;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->color_, output);
  }

  // required int32 width = 8;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->width(), output);
  }

  // required int32 length = 9;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->length(), output);
  }

  // optional int32 pairID = 10;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->pairid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:LaneClothidObjectFormat)
}

::google::protobuf::uint8* LaneClothidObjectFormat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LaneClothidObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_S_LANE];
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // required string name = 3 [default = "Clothid Line"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "LaneClothidObjectFormat.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // required int32 id = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->id(), target);
  }

  // repeated float clothidPar = 6;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteFloatToArray(6, this->clothidpar_, target);

  // required .Color color = 7;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, *this->color_, deterministic, target);
  }

  // required int32 width = 8;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->width(), target);
  }

  // required int32 length = 9;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->length(), target);
  }

  // optional int32 pairID = 10;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->pairid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LaneClothidObjectFormat)
  return target;
}

size_t LaneClothidObjectFormat::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:LaneClothidObjectFormat)
  size_t total_size = 0;

  if (has_name()) {
    // required string name = 3 [default = "Clothid Line"];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  if (has_color()) {
    // required .Color color = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->color_);
  }

  if (has_id()) {
    // required int32 id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  if (has_width()) {
    // required int32 width = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  if (has_length()) {
    // required int32 length = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->length());
  }

  if (has_type()) {
    // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_S_LANE];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  return total_size;
}
size_t LaneClothidObjectFormat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LaneClothidObjectFormat)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000005f) ^ 0x0000005f) == 0) {  // All required fields are present.
    // required string name = 3 [default = "Clothid Line"];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());

    // required .Color color = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->color_);

    // required int32 id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());

    // required int32 width = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());

    // required int32 length = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->length());

    // required .TP_OBJECT_TYPE type = 1 [default = TP_OBJECT_TYPE_S_LANE];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated float clothidPar = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->clothidpar_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->clothidpar_size());
    total_size += data_size;
  }

  // optional int32 pairID = 10;
  if (has_pairid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pairid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LaneClothidObjectFormat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LaneClothidObjectFormat)
  GOOGLE_DCHECK_NE(&from, this);
  const LaneClothidObjectFormat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LaneClothidObjectFormat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LaneClothidObjectFormat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LaneClothidObjectFormat)
    MergeFrom(*source);
  }
}

void LaneClothidObjectFormat::MergeFrom(const LaneClothidObjectFormat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LaneClothidObjectFormat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  clothidpar_.MergeFrom(from.clothidpar_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::LaneClothidObjectFormat::_default_name_.get(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_color()->::Color::MergeFrom(from.color());
    }
    if (cached_has_bits & 0x00000004u) {
      id_ = from.id_;
    }
    if (cached_has_bits & 0x00000008u) {
      width_ = from.width_;
    }
    if (cached_has_bits & 0x00000010u) {
      length_ = from.length_;
    }
    if (cached_has_bits & 0x00000020u) {
      pairid_ = from.pairid_;
    }
    if (cached_has_bits & 0x00000040u) {
      type_ = from.type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void LaneClothidObjectFormat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LaneClothidObjectFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LaneClothidObjectFormat::CopyFrom(const LaneClothidObjectFormat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LaneClothidObjectFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LaneClothidObjectFormat::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000005f) != 0x0000005f) return false;
  if (has_color()) {
    if (!this->color_->IsInitialized()) return false;
  }
  return true;
}

void LaneClothidObjectFormat::Swap(LaneClothidObjectFormat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LaneClothidObjectFormat::InternalSwap(LaneClothidObjectFormat* other) {
  using std::swap;
  clothidpar_.InternalSwap(&other->clothidpar_);
  name_.Swap(&other->name_);
  swap(color_, other->color_);
  swap(id_, other->id_);
  swap(width_, other->width_);
  swap(length_, other->length_);
  swap(pairid_, other->pairid_);
  swap(type_, other->type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LaneClothidObjectFormat::GetMetadata() const {
  protobuf_LaneClothidObjectFormat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_LaneClothidObjectFormat_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
