// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MovingObjectFormat.proto

#include "MovingObjectFormat.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class MovingObjectFormatDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MovingObjectFormat>
      _instance;
} _MovingObjectFormat_default_instance_;
namespace protobuf_MovingObjectFormat_2eproto {
void InitDefaultsMovingObjectFormatImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_BaseType_2eproto::InitDefaultsPos();
  protobuf_BaseType_2eproto::InitDefaultsOrient();
  protobuf_BaseType_2eproto::InitDefaultsContour();
  {
    void* ptr = &::_MovingObjectFormat_default_instance_;
    new (ptr) ::MovingObjectFormat();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MovingObjectFormat::InitAsDefaultInstance();
}

void InitDefaultsMovingObjectFormat() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMovingObjectFormatImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, osgfile_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, pos_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, heading_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, speed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MovingObjectFormat, contour_),
  6,
  0,
  7,
  1,
  2,
  3,
  4,
  5,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, sizeof(::MovingObjectFormat)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_MovingObjectFormat_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "MovingObjectFormat.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030MovingObjectFormat.proto\032\016BaseType.pro"
      "to\"\276\001\n\022MovingObjectFormat\022\035\n\004type\030\001 \002(\0162"
      "\017.TP_OBJECT_TYPE\022\014\n\004name\030\003 \002(\t\022\n\n\002id\030\004 \002"
      "(\005\022\017\n\007osgFile\030\005 \001(\t\022\021\n\003pos\030\006 \002(\0132\004.Pos\022\030"
      "\n\007heading\030\007 \002(\0132\007.Orient\022\026\n\005speed\030\010 \002(\0132"
      "\007.Orient\022\031\n\007contour\030\t \002(\0132\010.Contour"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 235);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MovingObjectFormat.proto", &protobuf_RegisterTypes);
  ::protobuf_BaseType_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MovingObjectFormat_2eproto

// ===================================================================

void MovingObjectFormat::InitAsDefaultInstance() {
  ::_MovingObjectFormat_default_instance_._instance.get_mutable()->pos_ = const_cast< ::Pos*>(
      ::Pos::internal_default_instance());
  ::_MovingObjectFormat_default_instance_._instance.get_mutable()->heading_ = const_cast< ::Orient*>(
      ::Orient::internal_default_instance());
  ::_MovingObjectFormat_default_instance_._instance.get_mutable()->speed_ = const_cast< ::Orient*>(
      ::Orient::internal_default_instance());
  ::_MovingObjectFormat_default_instance_._instance.get_mutable()->contour_ = const_cast< ::Contour*>(
      ::Contour::internal_default_instance());
}
void MovingObjectFormat::clear_pos() {
  if (pos_ != NULL) pos_->Clear();
  clear_has_pos();
}
void MovingObjectFormat::clear_heading() {
  if (heading_ != NULL) heading_->Clear();
  clear_has_heading();
}
void MovingObjectFormat::clear_speed() {
  if (speed_ != NULL) speed_->Clear();
  clear_has_speed();
}
void MovingObjectFormat::clear_contour() {
  if (contour_ != NULL) contour_->Clear();
  clear_has_contour();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MovingObjectFormat::kTypeFieldNumber;
const int MovingObjectFormat::kNameFieldNumber;
const int MovingObjectFormat::kIdFieldNumber;
const int MovingObjectFormat::kOsgFileFieldNumber;
const int MovingObjectFormat::kPosFieldNumber;
const int MovingObjectFormat::kHeadingFieldNumber;
const int MovingObjectFormat::kSpeedFieldNumber;
const int MovingObjectFormat::kContourFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MovingObjectFormat::MovingObjectFormat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_MovingObjectFormat_2eproto::InitDefaultsMovingObjectFormat();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MovingObjectFormat)
}
MovingObjectFormat::MovingObjectFormat(const MovingObjectFormat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  osgfile_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_osgfile()) {
    osgfile_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.osgfile_);
  }
  if (from.has_pos()) {
    pos_ = new ::Pos(*from.pos_);
  } else {
    pos_ = NULL;
  }
  if (from.has_heading()) {
    heading_ = new ::Orient(*from.heading_);
  } else {
    heading_ = NULL;
  }
  if (from.has_speed()) {
    speed_ = new ::Orient(*from.speed_);
  } else {
    speed_ = NULL;
  }
  if (from.has_contour()) {
    contour_ = new ::Contour(*from.contour_);
  } else {
    contour_ = NULL;
  }
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&type_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:MovingObjectFormat)
}

void MovingObjectFormat::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  osgfile_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&pos_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&pos_)) + sizeof(id_));
}

MovingObjectFormat::~MovingObjectFormat() {
  // @@protoc_insertion_point(destructor:MovingObjectFormat)
  SharedDtor();
}

void MovingObjectFormat::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  osgfile_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete pos_;
  if (this != internal_default_instance()) delete heading_;
  if (this != internal_default_instance()) delete speed_;
  if (this != internal_default_instance()) delete contour_;
}

void MovingObjectFormat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MovingObjectFormat::descriptor() {
  ::protobuf_MovingObjectFormat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MovingObjectFormat_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MovingObjectFormat& MovingObjectFormat::default_instance() {
  ::protobuf_MovingObjectFormat_2eproto::InitDefaultsMovingObjectFormat();
  return *internal_default_instance();
}

MovingObjectFormat* MovingObjectFormat::New(::google::protobuf::Arena* arena) const {
  MovingObjectFormat* n = new MovingObjectFormat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MovingObjectFormat::Clear() {
// @@protoc_insertion_point(message_clear_start:MovingObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*name_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!osgfile_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*osgfile_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(pos_ != NULL);
      pos_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(heading_ != NULL);
      heading_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(speed_ != NULL);
      speed_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(contour_ != NULL);
      contour_->Clear();
    }
  }
  if (cached_has_bits & 192u) {
    ::memset(&type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&id_) -
        reinterpret_cast<char*>(&type_)) + sizeof(id_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MovingObjectFormat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MovingObjectFormat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .TP_OBJECT_TYPE type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::TP_OBJECT_TYPE_IsValid(value)) {
            set_type(static_cast< ::TP_OBJECT_TYPE >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                1, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MovingObjectFormat.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string osgFile = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_osgfile()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->osgfile().data(), static_cast<int>(this->osgfile().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "MovingObjectFormat.osgFile");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .Pos pos = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_pos()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .Orient heading = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_heading()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .Orient speed = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_speed()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .Contour contour = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_contour()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MovingObjectFormat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MovingObjectFormat)
  return false;
#undef DO_
}

void MovingObjectFormat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MovingObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TP_OBJECT_TYPE type = 1;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // required string name = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MovingObjectFormat.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // required int32 id = 4;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->id(), output);
  }

  // optional string osgFile = 5;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->osgfile().data(), static_cast<int>(this->osgfile().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MovingObjectFormat.osgFile");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->osgfile(), output);
  }

  // required .Pos pos = 6;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->pos_, output);
  }

  // required .Orient heading = 7;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->heading_, output);
  }

  // required .Orient speed = 8;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *this->speed_, output);
  }

  // required .Contour contour = 9;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, *this->contour_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MovingObjectFormat)
}

::google::protobuf::uint8* MovingObjectFormat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MovingObjectFormat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TP_OBJECT_TYPE type = 1;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // required string name = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MovingObjectFormat.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // required int32 id = 4;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->id(), target);
  }

  // optional string osgFile = 5;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->osgfile().data(), static_cast<int>(this->osgfile().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "MovingObjectFormat.osgFile");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->osgfile(), target);
  }

  // required .Pos pos = 6;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, *this->pos_, deterministic, target);
  }

  // required .Orient heading = 7;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, *this->heading_, deterministic, target);
  }

  // required .Orient speed = 8;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        8, *this->speed_, deterministic, target);
  }

  // required .Contour contour = 9;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        9, *this->contour_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MovingObjectFormat)
  return target;
}

size_t MovingObjectFormat::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MovingObjectFormat)
  size_t total_size = 0;

  if (has_name()) {
    // required string name = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  if (has_pos()) {
    // required .Pos pos = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->pos_);
  }

  if (has_heading()) {
    // required .Orient heading = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->heading_);
  }

  if (has_speed()) {
    // required .Orient speed = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->speed_);
  }

  if (has_contour()) {
    // required .Contour contour = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->contour_);
  }

  if (has_type()) {
    // required .TP_OBJECT_TYPE type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  if (has_id()) {
    // required int32 id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  return total_size;
}
size_t MovingObjectFormat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MovingObjectFormat)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x000000fd) ^ 0x000000fd) == 0) {  // All required fields are present.
    // required string name = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());

    // required .Pos pos = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->pos_);

    // required .Orient heading = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->heading_);

    // required .Orient speed = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->speed_);

    // required .Contour contour = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->contour_);

    // required .TP_OBJECT_TYPE type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());

    // required int32 id = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional string osgFile = 5;
  if (has_osgfile()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->osgfile());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MovingObjectFormat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MovingObjectFormat)
  GOOGLE_DCHECK_NE(&from, this);
  const MovingObjectFormat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MovingObjectFormat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MovingObjectFormat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MovingObjectFormat)
    MergeFrom(*source);
  }
}

void MovingObjectFormat::MergeFrom(const MovingObjectFormat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MovingObjectFormat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_osgfile();
      osgfile_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.osgfile_);
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_pos()->::Pos::MergeFrom(from.pos());
    }
    if (cached_has_bits & 0x00000008u) {
      mutable_heading()->::Orient::MergeFrom(from.heading());
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_speed()->::Orient::MergeFrom(from.speed());
    }
    if (cached_has_bits & 0x00000020u) {
      mutable_contour()->::Contour::MergeFrom(from.contour());
    }
    if (cached_has_bits & 0x00000040u) {
      type_ = from.type_;
    }
    if (cached_has_bits & 0x00000080u) {
      id_ = from.id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void MovingObjectFormat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MovingObjectFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MovingObjectFormat::CopyFrom(const MovingObjectFormat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MovingObjectFormat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MovingObjectFormat::IsInitialized() const {
  if ((_has_bits_[0] & 0x000000fd) != 0x000000fd) return false;
  if (has_pos()) {
    if (!this->pos_->IsInitialized()) return false;
  }
  if (has_heading()) {
    if (!this->heading_->IsInitialized()) return false;
  }
  if (has_speed()) {
    if (!this->speed_->IsInitialized()) return false;
  }
  if (has_contour()) {
    if (!this->contour_->IsInitialized()) return false;
  }
  return true;
}

void MovingObjectFormat::Swap(MovingObjectFormat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MovingObjectFormat::InternalSwap(MovingObjectFormat* other) {
  using std::swap;
  name_.Swap(&other->name_);
  osgfile_.Swap(&other->osgfile_);
  swap(pos_, other->pos_);
  swap(heading_, other->heading_);
  swap(speed_, other->speed_);
  swap(contour_, other->contour_);
  swap(type_, other->type_);
  swap(id_, other->id_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MovingObjectFormat::GetMetadata() const {
  protobuf_MovingObjectFormat_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MovingObjectFormat_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
